name: concept-selection
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - ujson
  - jupytext
  - jupyter
  - ipykernel
  - pytorch
  - pytorch-cuda=12.1
  - pip
  - pip:
      - "setuptools<70.0.0"          # Fix for pkg_resources in simglucose
      - "gym<0.26,>=0.21"           # Namespace bridge for simglucose
      - shimmy                      # Required for gym/gymnasium conversion
      - stable-baselines3
      - "gymnasium[classic-control,atari,accept-rom-license]" # Engine + ROMs
      - ocatari
      - minigrid
      - "gurobipy<13.0,>=12.0"
      - opencv-python-headless