name: concept-selection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tqdm   
  - rich    
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - ujson
  - jupytext
  - jupyter
  - ipykernel
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1
  - pip
  - pip:
      - "setuptools<70.0.0"
      - "gym<0.26,>=0.21"
      - shimmy
      - stable-baselines3
      - "gymnasium[classic-control,atari,accept-rom-license]"
      - ocatari
      - minigrid
      - "gurobipy<13.0,>=12.0"
      - opencv-python-headless