_wandb:
    value:
        cli_version: 0.22.1
        e:
            vznqd10mucd4qsj5vu5w5tfimpn7wgxo:
                args:
                    - --gold_timesteps
                    - "4000000"
                    - --seed
                    - "42"
                    - --environment_string
                    - cart_pole
                    - --training_timesteps
                    - "10000"
                    - --num_concepts_selected
                    - "3"
                codePath: scripts/notebooks/new_methods/method_comparison.py
                codePathLocal: method_comparison.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "39995334656"
                        used: "18530971648"
                email: naveenr@andrew.cmu.edu
                executable: /usr0/home/naveenr/miniconda3/envs/food/bin/python
                git:
                    commit: 9d15ab17865f607158ff6b2c5988796704c40054
                    remote: https://github.com/naveenr414/concept_decisions.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-bfb2b081-9ff4-48eb-189c-56aa44938d4a
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-fa729db8-9d5a-029a-fa59-04ed4238b336
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4bd1abd2-815c-0aa3-3a93-d68bbc38ff26
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-1a5c8514-8f49-83da-da87-5debb01c66e1
                host: feif-ts2.isri.cmu.edu
                memory:
                    total: "507038375936"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /usr0/home/naveenr/projects/concept_decisions/scripts/notebooks/new_methods/method_comparison.py
                python: CPython 3.10.18
                root: /usr0/home/naveenr/projects/concept_decisions/scripts/notebooks/new_methods
                startedAt: "2025-11-18T13:45:56.108587Z"
                writerId: vznqd10mucd4qsj5vu5w5tfimpn7wgxo
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.18
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 512
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: cart_pole
learning_rate:
    value: 0.00025
n_epochs:
    value: 10
n_steps:
    value: 512
policy_kwargs:
    value:
        net_arch:
            - 128
            - 128
